// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TestPencarianTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() throws MalformedURLException {
    driver = new RemoteWebDriver(new URL("http://localhost:4444/wd/hub"), DesiredCapabilities.chrome());
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void testPencarian() {
    // Test name: Test_Pencarian
    // Step # | name | target | value
    // 1 | open | https://stockbit.com/#/stream | 
    driver.get("https://stockbit.com/#/stream");
    // 2 | setWindowSize | 1536x864 | 
    driver.manage().window().setSize(new Dimension(1536, 864));
    // 3 | click | css=.searchbox | 
    driver.findElement(By.cssSelector(".searchbox")).click();
    // 4 | type | css=.searchbox | bbri
    driver.findElement(By.cssSelector(".searchbox")).sendKeys("bbri");
    // 5 | sendKeys | css=.searchbox | ${KEY_ENTER}
    driver.findElement(By.cssSelector(".searchbox")).sendKeys(Keys.ENTER);
    // 6 | close |  | 
    driver.close();
  }
}
