# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestPencarian():
  def setup_method(self, method):
    self.driver = webdriver.Remote(command_executor='http://localhost:4444/wd/hub', desired_capabilities=DesiredCapabilities.CHROME)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testPencarian(self):
    # Test name: Test_Pencarian
    # Step # | name | target | value
    # 1 | open | https://stockbit.com/#/stream | 
    self.driver.get("https://stockbit.com/#/stream")
    # 2 | setWindowSize | 1536x864 | 
    self.driver.set_window_size(1536, 864)
    # 3 | click | css=.searchbox | 
    self.driver.find_element(By.CSS_SELECTOR, ".searchbox").click()
    # 4 | type | css=.searchbox | bbri
    self.driver.find_element(By.CSS_SELECTOR, ".searchbox").send_keys("bbri")
    # 5 | sendKeys | css=.searchbox | ${KEY_ENTER}
    self.driver.find_element(By.CSS_SELECTOR, ".searchbox").send_keys(Keys.ENTER)
    # 6 | close |  | 
    self.driver.close()
  
